package edu.sustech.cs209a.java2finalprojectdemo.helper;

/*
 * List all possible runtimeException type
 * https://www.android-doc.com/reference/java/lang/RuntimeException.html
 */
public enum MyRuntimeException {
    ACTIVITY_NOT_FOUND("ActivityNotFoundException"),
    ANDROID_RUNTIME("AndroidRuntimeException"),
    ANNOTATION_TYPE_MISMATCH("AnnotationTypeMismatchException"),
    ARITHMETIC("ArithmeticException"),
    ARRAY_STORE("ArrayStoreException"),
    BUFFER_OVERFLOW("BufferOverflowException"),
    BUFFER_UNDERFLOW("BufferUnderflowException"),
    CLASS_CAST("ClassCastException"),
    CONCURRENT_MODIFICATION("ConcurrentModificationException"),
    DOM("DOMException"),
    EMPTY_STACK("EmptyStackException"),
    ENUM_CONSTANT_NOT_PRESENT("EnumConstantNotPresentException"),
    FRAGMENT_INSTANTIATION("Fragment.InstantiationException"),
    GL("GLException"),
    ILLEGAL_ARGUMENT("IllegalArgumentException"),
    ILLEGAL_MONITOR_STATE("IllegalMonitorStateException"),
    ILLEGAL_STATE("IllegalStateException"),
    INCOMPLETE_ANNOTATION("IncompleteAnnotationException"),
    INDEX_OUT_OF_BOUNDS("IndexOutOfBoundsException"),
    INFLATE("InflateException"),
    LS("LSException"),
    MALFORMED_PARAMETERIZED_TYPE("MalformedParameterizedTypeException"),
    MEDIA_CODEC_CRYPTO("MediaCodec.CryptoException"),
    MISSING_RESOURCE("MissingResourceException"),
    NEGATIVE_ARRAY_SIZE("NegativeArraySizeException"),
    NETWORK_ON_MAIN_THREAD("NetworkOnMainThreadException"),
    NO_SUCH_ELEMENT("NoSuchElementException"),
    NO_SUCH_PROPERTY("NoSuchPropertyException"),
    NULL_POINTER("NullPointerException"),
    OPERATION_CANCELED("OperationCanceledException"),
    PARCEL_FORMAT("ParcelFormatException"),
    PARSE("ParseException"),
    PROVIDER("ProviderException"),
    RS_RUNTIME("RSRuntimeException"),
    REJECTED_EXECUTION("RejectedExecutionException"),
    REMOTE_VIEWS_ACTION("RemoteViews.ActionException"),
    RESOURCES_NOT_FOUND("Resources.NotFoundException"),
    SQL("SQLException"),
    SECURITY("SecurityException"),
    STALE_DATA("StaleDataException"),
    SURFACE_OUT_OF_RESOURCES("Surface.OutOfResourcesException"),
    SURFACE_HOLDER_BAD_SURFACE_TYPE("SurfaceHolder.BadSurfaceTypeException"),
    TIME_FORMAT("TimeFormatException"),
    TYPE_NOT_PRESENT("TypeNotPresentException"),
    UNDECLARED_THROWABLE("UndeclaredThrowableException"),
    UNSUPPORTED_DIGEST_ALGORITHM("UnsupportedDigestAlgorithmException"),
    UNSUPPORTED_OPERATION("UnsupportedOperationException"),
    WINDOW_MANAGER_BAD_TOKEN("WindowManager.BadTokenException"),
    WINDOW_MANAGER_INVALID_DISPLAY("WindowManager.InvalidDisplayException"),
///indirect
    ACCESS_CONTROL("AccessControlException"),
    ALREADY_CONNECTED("AlreadyConnectedException"),
    ARRAY_INDEX_OUT_OF_BOUNDS("ArrayIndexOutOfBoundsException"),
    BAD_PARCELABLE("BadParcelableException"),
    CANCELLATION("CancellationException"),
    CANCELLED_KEY("CancelledKeyException"),
    CLOSED_SELECTOR("ClosedSelectorException"),
    CONNECTION_PENDING("ConnectionPendingException"),
    CURSOR_INDEX_OUT_OF_BOUNDS("CursorIndexOutOfBoundsException"),
    DUPLICATE_FORMAT_FLAGS("DuplicateFormatFlagsException"),
    FORMAT_FLAGS_CONVERSION_MISMATCH("FormatFlagsConversionMismatchException"),
    FORMATTER_CLOSED("FormatterClosedException"),
//    FRAGMENT_INSTANTIATION("Fragment.InstantiationException"),
    ILLEGAL_BLOCKING_MODE("IllegalBlockingModeException"),
    ILLEGAL_CHARSET_NAME("IllegalCharsetNameException"),
    ILLEGAL_FORMAT_CODE_POINT("IllegalFormatCodePointException"),
    ILLEGAL_FORMAT_CONVERSION("IllegalFormatConversionException"),
    ILLEGAL_FORMAT("IllegalFormatException"),
    ILLEGAL_FORMAT_FLAGS("IllegalFormatFlagsException"),
    ILLEGAL_FORMAT_PRECISION("IllegalFormatPrecisionException"),
    ILLEGAL_FORMAT_WIDTH("IllegalFormatWidthException"),
    ILLEGAL_SELECTOR("IllegalSelectorException"),
    ILLEGAL_THREAD_STATE("IllegalThreadStateException"),
    INPUT_MISMATCH("InputMismatchException"),
    INVALID_MARK("InvalidMarkException"),
    INVALID_PARAMETER("InvalidParameterException"),
    KEY_CHARACTER_MAP_UNAVAILABLE("KeyCharacterMap.UnavailableException"),
    MISSING_FORMAT_ARGUMENT("MissingFormatArgumentException"),
    MISSING_FORMAT_WIDTH("MissingFormatWidthException"),
    NO_CONNECTION_PENDING("NoConnectionPendingException"),
    NON_READABLE_CHANNEL("NonReadableChannelException"),
    NON_WRITABLE_CHANNEL("NonWritableChannelException"),
    NOT_YET_BOUND("NotYetBoundException"),
    NOT_YET_CONNECTED("NotYetConnectedException"),
    NUMBER_FORMAT("NumberFormatException"),
    OVERLAPPING_FILE_LOCK("OverlappingFileLockException"),
    PATTERN_SYNTAX("PatternSyntaxException"),
    RS_DRIVER("RSDriverException"),
    RS_ILLEGAL_ARGUMENT("RSIllegalArgumentException"),
    RS_INVALID_STATE("RSInvalidStateException"),
    READ_ONLY_BUFFER("ReadOnlyBufferException"),
    RECEIVER_CALL_NOT_ALLOWED("ReceiverCallNotAllowedException"),
    SQLITE_ABORT("SQLiteAbortException"),
    SQLITE_ACCESS_PERM("SQLiteAccessPermException"),
    SQLITE_BIND_OR_COLUMN_INDEX_OUT_OF_RANGE("SQLiteBindOrColumnIndexOutOfRangeException"),
    SQLITE_BLOB_TOO_BIG("SQLiteBlobTooBigException"),
    SQLITE_CORRUPT("SQLiteDatabaseCorruptException"),
    SQLITE_LOCKED("SQLiteDatabaseLockedException"),
    SQLITE_DATATYPE_MISMATCH("SQLiteDatatypeMismatchException"),
    SQLITE_DISK_IO("SQLiteDiskIOException"),
    SQLITE_DONE("SQLiteDoneException"),
    SQLITE("SQLiteException"),
    SQLITE_FULL("SQLiteFullException"),
    SQLITE_MISUSE("SQLiteMisuseException"),
    SQLITE_OUT_OF_MEMORY("SQLiteOutOfMemoryException"),
    SQLITE_READ_ONLY_DATABASE("SQLiteReadOnlyDatabaseException"),
    SQLITE_TABLE_LOCKED("SQLiteTableLockedException"),
    STRING_INDEX_OUT_OF_BOUNDS("StringIndexOutOfBoundsException"),
    UNKNOWN_FORMAT_CONVERSION("UnknownFormatConversionException"),
    UNKNOWN_FORMAT_FLAGS("UnknownFormatFlagsException"),
    UNRESOLVED_ADDRESS("UnresolvedAddressException"),
    UNSUPPORTED_ADDRESS_TYPE("UnsupportedAddressTypeException"),
    UNSUPPORTED_CHARSET("UnsupportedCharsetException");

    private final String exceptionName;

    MyRuntimeException(String exceptionName) {
        this.exceptionName = exceptionName;
    }

    public String getName() {
        return exceptionName;
    }
}
